In [6]:
import pandas as pd

### Задание 1

In [7]:
data = pd.read_csv('ml-25m/ratings.csv')

res = data[(data['rating']==5)].value_counts(['movieId']).head(1).to_frame()


mov = pd.read_csv('ml-25m/movies.csv')

result = res.merge(mov, on='movieId', how='left')

result.filter(['movieId', 'title'])

   movieId                             title
0      318  Shawshank Redemption, The (1994)

In [8]:
res

             0
movieId
318      39553

### Задание 2

In [10]:
data = pd.read_csv('10/power.csv')


data_fil = (data[((data['country'] == 'Latvia') |  
                  (data['country'] == 'Lithuania') |  
                  (data['country'] == 'Estonia') ) & # отбор по странам
                 ((data['year'] < 2010) & (data['year'] > 2005)) &  # отбор по категориям
                    ((data['category'] == 4) | (data['category'] == 12) | (data['category'] == 21)) & # отбор по категориям
                    (data['quantity'] > 0)]) # без отрицательных значений

res = data_fil.groupby(['country']).sum().filter(['country', 'quantity'])
res

           quantity
country
Estonia     42184.0
Latvia      35860.0
Lithuania   86511.0

### Задание 3

In [11]:
pd.read_html('https://fortrader.org/quotes')[0]

                           Название   Цена  Изменение  Изменение(%)  Обновлено
0  EURRUB Курс евро к рублю сегодня  86.86       -0.2         -0.23        NaN
1       USDRUB Курс рубля к доллару  74.01        0.0          0.01        NaN

In [6]:
pd.read_html('https://fortrader.org/quotes')[3]

,Название,Цена,Изменение,Изменение(%),Обновлено
0,ВТБ Акции ВТБ,0.048975,-0.00002,-0.04082,NaN
1,Газпром Акции газпрома,295.10,-0.12000,-0.04000,NaN
2,Лукойл Акции Лукойл,6 655.0,0.00000,0.00000,NaN
3,Роснефть Акции Роснефти,577.85,0.00000,0.00000,NaN
4,Сбербанк Акции Сбербанка,303.55,-0.01000,-0.00000,NaN
5,Сургутнефтегаз Акции Сургутнефтегаза,35.550,-0.01000,-0.02800,NaN
6,Норникель Акции Норникель,24 778,-2.00000,-0.00000,NaN
7,Аэрофлот Акции Аерофлота,68.72,-0.02000,-0.03000,NaN
8,Северсталь Акции Северсталь,1 624.20,-0.60000,-0.04000,NaN
9,Транснефть Акции Транснефть,174 450,-50.00000,-0.00000,NaN
10,Ростелеком Курс акций ростелекома,99.50,0.00000,0.00000,NaN
11,РУСАЛ Акции РУСАЛ (RUAL),49.540,0.00000,0.00000,NaN
12,Детский мир iDreamSky Technology Limited,143.70,0.00000,0.00000,NaN
13,Петропавловск Акции Петропавловск,23.00,-0.04000,-0.17000,NaN
14,Алроса Акции АЛРОСА (ALRS),130.840,-0.15000,-0.11500,NaN
15,Магнит Акции Магнит (MGNT),5 322.0,-0.50000,-0.00000,NaN
16,НМЛК Акции НЛМК (NLMK),233.780,-0.02000,-0.00900,NaN
17,М.видео Акции М.видео (MVID),618.40,-0.20000,-0.03000,NaN
18,"Газпром нефть Акции ""Газпром нефть"" (SIBN)",438.60,-0.20000,-0.05000,NaN
19,НМТП Акции НМТП (NMTP),6.9500,0.00000,0.00000,NaN
20,Полиметалл Акции Полиметалл (POLY),1 621.60,-0.40000,-0.02000,NaN
21,Полюс Золото Акции Полюс Золото (PLZL),14 190.0,0.00000,0.00000,NaN
22,НОВАТЭК Акции НОВАТЭК (NVTK),1 612.40,0.00000,0.00000,NaN
23,РусГидро Акции РусГидро (HYDR),0.8334,-0.00050,-0.06000,NaN
24,Татнефть Акции Татнефть (TATN),519.10,0.00000,0.00000,NaN
25,"АФК Система Акции АФК ""Система"" (AFKS)",31.150,-0.02200,-0.07100,NaN
26,МТС Акции МТС,319.30,-0.05000,-0.02000,NaN
27,Башнефть Акции Башнефть (BANE),1 477.0,-7.00000,-0.50000,NaN
28,Яндекс Акции Яндекс (YNDX),5 235.8,0.00000,0.00000,NaN
29,X5 Retail Group Акции X5 Retail Group (FIVE),2 478.50,-0.50000,-0.02000,NaN
30,ФСК ЕЭС Акции ФСК ЕЭС (FEES),0.22900,-0.00016,-0.06982,NaN
31,Мечел Акции Мечел (MTLR),76.80,0.00000,0.00000,NaN
32,МосБиржа Акции МосБиржа (MOEX),171.51,-0.04000,-0.02000,NaN
33,Интер РАО Акции Интер РАО (IRAO),4.70,-0.00000,-0.09000,NaN
34,"Mail.ru Акции Mail.ru (MAIL, ДР)",1 616.20,0.20000,0.01000,NaN
35,Киви Акции Киви (QIWI),760.0,-1.50000,-0.20000,NaN
36,"Лента Акции Лента (LNTA, ДР)",247.80,0.00000,0.00000,NaN
37,"Тинькофф Акции Тинькофф (TCSG, др)",6 625.00,0.00000,0.00000,NaN
38,Озон Акции Озон (Ozon),4 130.00,-3.00000,-0.07000,NaN